#!/bin/bash

# Install Composer dependencies
composer install -d "/var/www/backend"

echo "Initialize Script in Container"
echo "Project Name = "${COMPOSE_PROJECT_NAME}
echo "Front End Domain = "${FRONT_END_DOMAIN}
echo "Back End Domain = "${BACK_END_DOMAIN}
echo "Database Name = "$DATABASE_NAME
echo "Database User = "${DATABASE_USER}
echo "Database Password = "${DATABASE_PASSWORD}

# Create the laravel project
composer create-project --prefer-dist laravel/laravel tmp "8.*"

# Wait until the project is created
wait
sh -c "mv -n tmp/.* ./ && mv tmp/* ./ && rm -Rf tmp"

# Create the backend .env file
cat > "/var/www/backend/.env" << EOF
APP_NAME=$COMPOSE_PROJECT_NAME
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://backend.dev.test

LOG_CHANNEL=single

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=$DATABASE_NAME
DB_USERNAME=$DATABASE_USER
DB_PASSWORD=$DATABASE_PASSWORD

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
EOF

# Generate application key
php "/var/www/backend/artisan" key:generate --ansi

# Make sure the MySQL database is available
echo 'Waiting for MySQL to be available'
count=1
while [ $count -le 10 ] && ! mysql -u$DATABASE_USER -p$DATABASE_PASSWORD -h mysql -P3306 -e 'exit' ; do
    sleep 5
    ((count++))
done
if [ "$count" -ge 10 ]; then
    echo >&2 'error: failed to connect to MySQL after 10 attempts'
    exit 1
fi
echo 'MySQL connection successful!'

# Database
php "/var/www/backend/artisan" migrate
